version: "3.9"
services:
  # FastAPI
  api:
    build: ./app # local app dir
    container_name: ml_api 
    ports:
      - "8000:8000"
    volumes:
      # local app / container app from Dockerfile
      - ./app:/app

  # Streamlit
  streamlit:
    build: ./app
    container_name: ml_ui
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
    depends_on:
      - api # streamlit이 fastapi가 의존하는 상태
